# version: '3'
services:
#first image 
  web:
    image: "makarmarkov/land_devops:${TAG}"
    container_name: "web-container-${TAG}"
    volumes: 
      - "./volume:/tmp/"
    # build: 
    #   context: ./
    #   dockerfile: ./dockerfile
    ports:
      - 8081:80
    networks:
      - landing_network

networks:
  landing_network:
