# Название вашего пайплайна
name: Version update runner

#Триггер на события, которые производятся по пушу или мерджу 
# on:
#   push:
#     branches: [ "master", "develop" ]
on:
  pull_request:
    # На какие типы событий он должен работать
    #types: [opened, synchronize, reopened, closed, assigned, unassigned, labeled, unlabeled, edited]
    types: [closed]
    branches:
      - release
env:
  TYPE_BRANCH: none
  NAME_VERSION_FILE: version

#JOBS list for update versions 
jobs:
  pre-merge-check:
    runs-on: ubuntu-latest
    outputs:
      type_branch_f: ${{ steps.feature-branch.outputs.type_branch_f }}
      type_branch_h: ${{ steps.hotfix-branch.outputs.type_branch_h }}
    steps:
      
      # use special lib for parse branch names 
      - name: Get branch names
        id: branch-names
        uses: tj-actions/branch-names@v8
      
      # print info about variables and parsed branches
      - name: Print info
        id: print-info
        run: |
          echo "EVENT NAME    : ${{ github.event_name }}"
          echo "ACTION        : ${{github.event.action }}"
          echo "EVENT NAME    : ${{ github.event_name }}"
          echo "IS            : ${{github.event.pull_request.merged}}"
          echo "CURRENT BRANCH: ${{ steps.branch-names.outputs.current_branch }}"
          echo "REF           : ${{github.ref}}"
          echo "REF NAME      :${{github.ref_name}}"
          echo "DEFAULT BRANCH:${{ steps.branch-names.outputs.default_branch }}"
      
      # check if branch feature 
      - name: Check [FEATURE]
        id: feature-branch
        if: contains(steps.branch-names.outputs.current_branch,'feature')
        run: | 
          echo "ЗАмержена ветка Feature. Требуется произвести обновлении файла version в части минорной версии"
          echo "type_branch_f=feature" >> "$GITHUB_OUTPUT"
      
      # TASK for check if branch hotfix
      - name: Check [HOTFIX] 
        id: hotfix-branch
        if: contains(steps.branch-names.outputs.current_branch,'hotfix')
        run: | 
          echo "ЗАмержена ветка hotfix. Требуется произвести обновлении файла version в части патч версии"
          echo "type_branch_h=hotfix" >> "$GITHUB_OUTPUT"
        
        
  # Проверка файла на наличие в репозитории 
  version-file-check:
    runs-on: ubuntu-latest
    # чего ждем. Т.е. начнем выполняться только после того, как отработает джоба, указанная выше
    needs: pre-merge-check
    # постепенно выполняем шаги
    steps:
      - name: Verify current directory 
        run: pwd
      - name: Print info about directory 
        run: ls -la
      - name: Print info about ${{env.NAME_VERSION_FILE}} 
        run: ls -la
        
  # Производим определение какую версию нам обновлять       
  update-version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: version-file-check
    env:
      type_branch_f: ${{needs.pre-merge-check.outputs.type_branch_f}}
    steps:
        # обновляем минорную версию
      - name: Check update version MINOR
        run: | 
          echo " new $type_branch_f"
        #if: ${{ env.TYPE_BRANCH == 'feature' }}
        #run: echo "Update minor version"

        # обновляем патч версию
      - name: Check update version PATCH 
        if: ${{ env.TYPE_BRANCH == 'hotfix' }}
        run: echo "Update hotfix version"
      
      # checkout on branch 
      - name: checkout
        uses: actions/checkout@v2

      # save current date 
      - name: save current date
        run: |
          date >> time.txt 

      # setup user which will be commit
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      #commit
      - name: commit
        run: |
          # Stage the file, commit and push
          git add .
          git commit -m "update time.txt"
          git push origin release

      #   # Ничего не обновляем и выходим
      # - name: Check update version MINOR 
      #   if: ${{ env.TYPE_BRANCH == 'none' }}
      #   run: | 
      #     echo "Nothing to update"
      #     # exit 0
              
      
    

  
