# Название вашего пайплайна
name: Version update runner

#Триггер на события, которые производятся по пушу или мерджу 
# on:
#   push:
#     branches: [ "master", "develop" ]
on:
  pull_request:
    # На какие типы событий он должен работать
    #types: [opened, synchronize, reopened, closed, assigned, unassigned, labeled, unlabeled, edited]
    types: [closed]
    branches:
      - release

# Создаем job
jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check on existing VERSION file
        shell: bash
        run: echo "check VERSION file in ROOT directory"
      
      - name: Get branch names
        id: branch-names
        uses: tj-actions/branch-names@v8
      
      - name: Print info
        run: |
          echo "EVENT NAME    : ${{ github.event_name }}"
          echo "ACTION        : ${{github.event.action }}"
          echo "EVENT NAME    : ${{ github.event_name }}"
          echo "IS            : ${{github.event.pull_request.merged}}"
          echo "CURRENT BRACNH: ${{ steps.branch-names.outputs.current_branch }}"
          echo "REF           : ${{github.ref}}"
          echo "REF NAME      :${{github.ref_name}}"
          echo "DEFAULT BRANCH:${{ steps.branch-names.outputs.default_branch }}"
          
      - name: Check if bracnh contains FEATURE
        if:  ${{steps.branch-names.outputs.current_branch}}  == 'feature*'
        run: echo " for feature"

      - name: Check if bracnh contains FEATURE 2
        if:  contains(${{ steps.branch-names.outputs.current_branch }},'feature')
        run: echo "ech for feature 2"

      - name: Check if bracnh contains FEATURE 3
        if:  ${{steps.branch-names.outputs.current_branch}}  == 'fe123ature'
        run: echo "ech for feature 3"
        # Outputs: "feature/test" current PR branch.
