name: Deploy appllication to enviroments
on:
  workflow_call:
    inputs:  
      version:
        type: string
        required: true
        description: "Version of application. Tag from gitlab"
      container_name:
        type: string
        required: true
        description: "Name of container."
      image_full_name:
        type: string
        required: true
        description: "name of image from dockerhub"

# declare version of application 
env:
  TAG: ${{ inputs.version || 'latest' }}
  CONTAINER_NAME: ${{ inputs.container_name || 'land_devops:v0.16.23'}}
  IMAGE_NAME: ${{ inputs.image_full_name || 'makarmarkov/land_devops:v0.16.2'}}
  PROD_ENV: "prod.env"

# jobs for deploy applications 
jobs: 
  deploy-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev,test,stage]
    steps:
      - name: ewqe
        run: echo "start on ${{matrix.environment}}"

  # special job for deploy to prod
  deploy-prod: 
    environment: prod
    runs-on: self-hosted
    name: PROD
    steps:
      # checkout 
      - name: checkout on release branch
        uses: actions/checkout@v2
  
      # get data about container
      - name: List data about container 
        run: | 
          docker ps -a 
          docker image ls

      # docker stop all containers 
      # and delete all images
      # - name: Stop and Delete images 
      #   run: |
      #     FOR /f "tokens=*" %i IN ('docker ps -q') DO docker stop %i

      # docker stop $(docker ps -a -q)
      # docker rm $(docker ps -a -q)
          #      touch ${{ env.PROD_ENV }}
          # echo "VERSION=${{ env.TAG }}" >> ${{ env.PROD_ENV }}
          # echo "CONTAINER_NAME=${{ env.CONTAINER_NAME }}" >> ${{ env.PROD_ENV }}
          # echo "DOCKER_HUB_IMAGE = ${{ env.IMAGE_NAME }}" >> ${{ env.PROD_ENV }}  
      
      # create file prod.env file for deploy application 
      - name: Create .ENV
        shell: powershell
        run : |
          New-Item ${{ env.PROD_ENV }} -ItemType file
          Add-Content ${{ env.PROD_ENV }} "VERSION=${{ env.TAG }}"
          Add-Content ${{ env.PROD_ENV }} "CONTAINER_NAME=${{ env.CONTAINER_NAME }}"
          Add-Content ${{ env.PROD_ENV }} "DOCKER_HUB_IMAGE = ${{ env.IMAGE_NAME }}"

      # Start new version of application 
      - name: Run container ${{env.IMAGE_NAME}} for file ${{ env.PROD_ENV }}
        run: |  
          docker-compose -f docker-compose.yml --env-file ${{ env.PROD_ENV }} up