name: Deploy appllication to enviroments
on:
  workflow_call:
    inputs:  
      version:
        type: string
        required: true
        description: "Version of application. Tag from gitlab"

# declare version of application 
env:
  TAG: ${{ inputs.version|| 'latest' }}

jobs: 
  deploy-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev,test,stage]
    steps:
      - name: ewqe
        run: echo "start on ${{matrix.environment}}"

  deploy-prod: 
    environment: prod
    needs: [deploy-test] 
    runs-on: ubuntu-latest
    name: PROD
    steps:
      # checkout 
      - name: checkout on release branch
        uses: actions/checkout@v2
  
      # get data about container
      - name: List data about container 
        run: | 
          docker status 
          docker ps -a 
          docker image -ls

      # docker stop all containers 
      # and delete all images
      - name: Stop and Delete images 
        run: |
          docker stop $(docker ps -a -q)
          docker rm $(docker ps -a -q)
      
      # create file   
      - name: Create .ENV
        run : |
          touch .env
          echo "TAG=${{ env.TAG }}" >> .env  

      # Start new version of application 
      - name: Run container ${{env.TAG}}
        run: |  
          docker compose up